# Your Solution
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: book-catalog
        image: souvik72p221382131ctr.azurecr.io/book-catalog:1
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "8001"
        - name: DATABASE_URL
          value: "postgresql://books_db_task72p_user:HLVuFYUd3Z02t822QKAMNqniTA2SRjrg@dpg-crh2bdlsvqrc73877130-a.oregon-postgres.render.com/books_db_task72p"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management
        image: souvik72p221382131ctr.azurecr.io/inventory-management:1
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "8002"
        - name: DATABASE_URL
          value: "postgresql://books_db_task72p_user:HLVuFYUd3Z02t822QKAMNqniTA2SRjrg@dpg-crh2bdlsvqrc73877130-a.oregon-postgres.render.com/books_db_task72p"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
